### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by Cyclic3** [godarklight/DarkMultiPlayer#451]
### Environment
- OS: N/A
- Mono: N/A
### Description
Would it be possible for @godarklight to setup a docker hub image which automatically builds from this? It appears that non-owners cannot do this, and so I would need to maintain a mirror (which could die, like the others). This would only take a couple of minutes to set up, and would allow me to easily deploy DMP on my server cluster.

Thank you very much!

**Comment by tgxn** [comment]
I created a `Dockerfile` to run this server in:

```Dockerfile
FROM alpine:latest as downloader

ARG DMP_VERSION
RUN wget  "https://d-mp.org/builds/release/${DMP_VERSION}/DMPServer.zip"
RUN unzip DMPServer.zip -d / -o

FROM mono:latest
COPY --from=downloader /DMPServer /DMPServer

WORKDIR /DMPServer
EXPOSE 6702
ENTRYPOINT ["mono", "./DMPServer.exe"]
```

I use this with docker-compose:

```yaml
version: "3.3"
services:
  dark-mp:
    container_name: game_ksp_darkmp
    image: ksp-darkmp:local
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DMP_VERSION: v0.3.8.0
    ports:
      - "6702:6702"
    volumes:
      - "./ServerData/Config:/LMPServer/Config"
      - "./ServerData/Universe:/LMPServer/Universe"
      - "./ServerData/Plugins:/LMPServer/Plugins"
      - "./ServerData/logs:/LMPServer/logs"
    restart: unless-stopped
```
